#!/bin/bash

set -e
cd `dirname $0`

function menv() {
    node ../index.js "$@"
}

function expect() {
    if [[ "$1" != "$2" ]]; then
        echo "[fail] expect=$1, actual=$2"
        exit 1
    fi
}
function expectThrow() {
    if "$@"; then
        echo "expect throw, but not happen. cmd=$@"
        exit 1
    fi
}

# clean
rm -rf build/*

menv build
echo '[ok] build'

expect dev1 $(menv echo dev1 __env__)
expect dev150 $(menv echo dev1 b.c)
expect "a b c" "$(menv echo dev1 b.x)"
echo '[ok] echo'

expect env-with-dir $(menv echo d1/d2/env-with-dir __env__)
expect 2 $(menv echo d1/d2/env-with-dir v-x)
expect 1 $(menv echo d1/d2/env-with-dir v)
echo '[ok] env with dir'

expectThrow menv echo dev1 b.c.no-exist
echo '[ok] config no exist'

expect dev1 $(menv echo dev1 b.env)
expect 3 $(menv echo dev1 b._a)
echo '[ok] substitute'

echo '[ok] all success.'
