#!/bin/bash

ver=$1
if [[ -z $ver ]]; then
    exit 1
fi

pkg/pkg

find . -name package.json ! -path '*/node_modules/*'| while read p; do 
    d=`dirname $p`
    cd $d
    npm version -no-git-tag-version $ver
    npm pu
    cd - &>/dev/null
done
