#!/bin/bash

if which menv &>/dev/null; then
    menv "$@"
    exit
fi

ver=1.2.2

set -e

# get os
uname_out="$(uname -s)"
case "${uname_out}" in
    Linux*)     os=linux;;
    Darwin*)    os=macos;;
    CYGWIN*)    os=win;;
    MINGW*)     os=win;;
    *)          os="unsupported:${uname_out}"
esac

oldwd=`pwd`
bindir=`dirname $0`

# install
cd $bindir
if [ ! -f menv-version ] || ! cat menv-version|grep -x $ver &>/dev/null; then
    echo -n "fisrt time using menv, install ..." >&2
    curl -s https://registry.npmjs.org/menv-$os/-/menv-$os-$ver.tgz |tar --strip-components=1 -zx package/menv-$os
    chmod a+x menv-$os
    echo $ver > menv-version
    if ! grep -x 'menv-\*' .gitignore &>/dev/null; then
        echo 'menv-*' >> .gitignore
    fi
    echo "done" >&2
fi
cd $oldwd

# run real "menv"
$bindir/menv-$os "$@"
